In [110]:
# importing the required lib
import pandas as pd
import numpy as np

In [111]:
# the dataset i had used for this project is downloaded from this link below
#https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata

In [112]:
#Loading the dataset
credits_df=pd.read_csv("D:/Raush_byte/archive (12)/tmdb_5000_credits.csv")
movies_df=pd.read_csv("D:/Raush_byte/archive (12)/tmdb_5000_movies.csv")

In [113]:
#just checking the head of the loaded dataset
credits_df.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [114]:
movies_df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [115]:
print(credits_df.shape)
print(movies_df.shape)

(4803, 4)
(4803, 20)

In [116]:
# we had 2 sets csv file  now we are checking the columns in both the csv file
print(credits_df.columns)
print(movies_df.columns)

Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')
Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')

In [117]:
# in this data set we had the column movie_id from the credits_df and id from the movies_dfby using this columns we can join the both the csv file
# i am renaming the "movie_id" from the credit_df to "id" so it will match
credits_df.rename(columns={"movie_id":"id"}, inplace=True)

# merging both csv file
merged_df=movies_df.merge(credits_df,on="id")

print(merged_df.shape)

(4803, 23)

In [118]:
# checking the head of the merged_df
merged_df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [119]:
# now lets check the dataset
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   str
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title_x               4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
 20  title_y               4803 non-null   str
 21  cast                  4803 non-null   str
 22  crew                  4803 non-null   str
dtypes: float64(3), int64(4), str(16)
memory usage: 39.2 MB

In [120]:
merged_df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'title_y', 'cast', 'crew'],
      dtype='str')

In [121]:
# now we are checking the null values
print(merged_df.isna().sum())

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title_x                    0
vote_average               0
vote_count                 0
title_y                    0
cast                       0
crew                       0
dtype: int64

In [122]:
# here we are cheking any duplicate values in it
print(merged_df.duplicated().sum())

0

In [123]:
# we had find that ther are some missing value so we are going to fill that mixing value
merged_df['runtime'] = merged_df['runtime'].fillna(merged_df['runtime'].median())

merged_df['tagline'] = merged_df['tagline'].fillna('')

In [124]:
# i had planed to droe the null value in the relese_data because if i use ffill or some other method it would give the wrong date
# This deletes just the row where release_date is missing
merged_df.dropna(subset=['release_date'], inplace=True)

In [125]:
# now iam filling the null value with the fill up value
merged_df['homepage'] = merged_df['homepage'].fillna('No Website')

In [126]:
# now iam filling it with simple string
merged_df['overview'] = merged_df['overview'].fillna('No Overview')

In [127]:
# now checking is there any other null values is left there
merged_df.isna().sum()

budget                  0
genres                  0
homepage                0
id                      0
keywords                0
original_language       0
original_title          0
overview                0
popularity              0
production_companies    0
production_countries    0
release_date            0
revenue                 0
runtime                 0
spoken_languages        0
status                  0
tagline                 0
title_x                 0
vote_average            0
vote_count              0
title_y                 0
cast                    0
crew                    0
dtype: int64

In [128]:
# in this dataset the relese_date is in the str format
merged_df["release_date"]=pd.to_datetime(merged_df["release_date"])

In [129]:
# extract the year into a new column
merged_df["release_year"] = merged_df["release_date"].dt.year

# extract the month into a new column
merged_df["release_month"]=merged_df["release_date"].dt.month

In [130]:
merged_df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'title_y', 'cast', 'crew', 'release_year',
       'release_month'],
      dtype='str')

In [131]:
print(merged_df[
    ['original_title', 'genres', 'keywords', 'overview']
].head())

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...
4  [{"id": 818, "name": "based on novel"}, {"id":...

                                            overview
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...
3  Following the death of District Attorney Harve...
4  John Carter is a war-weary, former military ca...

In [132]:
# now we are trying to extract the gener name form this 
import ast

def extract_names(text):
    try:
        items = ast.literal_eval(text)
        return [item['name'] for item in items]
    except (ValueError, SyntaxError, TypeError):
        return []

merged_df['genres_list'] = merged_df['genres'].apply(extract_names)

merged_df['keywords_list'] = merged_df['keywords'].apply(extract_names)

In [133]:
print(merged_df[
    ['original_title', 'genres_list', 'keywords_list', 'overview']
].head())

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                     genres_list  \
0  [Action, Adventure, Fantasy, Science Fiction]
1                   [Adventure, Fantasy, Action]
2                     [Action, Adventure, Crime]
3               [Action, Crime, Drama, Thriller]
4           [Action, Adventure, Science Fiction]

                                       keywords_list  \
0  [culture clash, future, space war, space colon...
1  [ocean, drug abuse, exotic island, east india ...
2  [spy, based on novel, secret agent, sequel, mi...
3  [dc comics, crime fighter, terrorist, secret i...
4  [based on novel, mars, medallion, space travel...

                                            overview
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...
3  Following the death of District Attorney Harve...
4  John Carter is a war-weary, former military ca...

In [134]:
#compaing the features
merged_df['overview'] = merged_df['overview'].fillna('')

merged_df['combined_features'] = (
    merged_df['overview'] + ' ' +
    merged_df['genres_list'].apply(lambda x: ' '.join(x)) + ' ' +
    merged_df['keywords_list'].apply(lambda x: ' '.join(x))
)

print(merged_df[
    ['original_title', 'combined_features']
].head(3))

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre

                                   combined_features
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...

In [135]:
# here we are appling the counter vector
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(
    max_features=5000,
    stop_words='english'
)

feature_matrix = cv.fit_transform(
    merged_df['combined_features']
)

print("Feature matrix shape:", feature_matrix.shape)

Feature matrix shape: (4802, 5000)

In [136]:
# calculating the movie similarity using the cosine similarty
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(feature_matrix)

print("Similarity matrix shape:", similarity_matrix.shape)

Similarity matrix shape: (4802, 4802)

In [137]:
print("Total movies:", len(merged_df))
print("Total movie features:", feature_matrix.shape[1])
print("Similarity between first two movies:",
      similarity_matrix[0][1])

Total movies: 4802
Total movie features: 5000
Similarity between first two movies: 0.0781166566864507

In [ ]:

movie_indicies = pd.Series(merged_df.index, index=merged_df['original_title'].str.lower()).drop_duplicates()

# Your existing function code can now run safely:
def recommended_movie(movie_title, top_n=10):
    movie_title = movie_title.strip().lower()
    ...

def recommended_movie(movie_title, top_n=10):
    movie_title = movie_title.strip().lower()
    
    if movie_title not in movie_indicies.index:
        print("Movie not found. Please check the title.")
        return
    
    # 1. Get the index of the selected movie
    idx = movie_indicies[movie_title]
    
    # Handle duplicate titles if idx returns a pandas Series instead of a single int
    if isinstance(idx, pd.Series):
        idx = idx.iloc[0]
        
    # 2. Get the similarity scores for all movies with that movie
    similarity_scores = list(enumerate(similarity_matrix[idx]))
    
    # 3. Sort the movies based on similarity scores in descending order
    sorted_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    
    # 4. Get the indices of the top_n similar movies (excluding the movie itself)
    top_movie_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    
    # 5. Return the titles of the top similar movies
    return merged_df['original_title'].iloc[top_movie_indices].tolist()

# Test the function
print(recommended_movie('avatar'))

['Aliens', 'Mission to Mars', 'Moonraker', 'Silent Running', 'Spaceballs', 'Alien', 'Alien³', 'Lifeforce', 'Lost in Space', 'Planet of the Apes']

In [ ]:

merged_df.to_csv("cleaned_movies.csv", index=False)


import pickle

with open("similarity_matrix.pkl", "wb") as f:
    pickle.dump(similarity_matrix, f)

print("Files saved successfully!")

Files saved successfully!

In [140]:
final_df=pd.read_csv("cleaned_movies.csv")
final_df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,vote_average,vote_count,title_y,cast,crew,release_year,release_month,genres_list,keywords_list,combined_features
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009,12,"['Action', 'Adventure', 'Fantasy', 'Science Fi...","['culture clash', 'future', 'space war', 'spac...","In the 22nd century, a paraplegic Marine is di..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007,5,"['Adventure', 'Fantasy', 'Action']","['ocean', 'drug abuse', 'exotic island', 'east...","Captain Barbossa, long believed to be dead, ha..."